local skillranks = {
    ["BLM"] = {
        ["Club"] = "C+",
        ["Dagger"] = "D",
        ["Dark"] = "A-",
        ["Elemental"] = "A+",
        ["Enfeebling"] = "C+",
        ["Enhancing"] = "E",
        ["Evasion"] = "E",
        ["Scythe"] = "E",
        ["Staff"] = "B-",
        ["Throwing"] = "D",
    },
    ["BLU"] = {
        ["Blue"] = "A+",
        ["Club"] = "B-",
        ["Evasion"] = "C-",
        ["Parrying"] = "D",
        ["Sword"] = "A+",
    },
    ["BRD"] = {
        ["Club"] = "D",
        ["Dagger"] = "B-",
        ["Evasion"] = "D",
        ["Parrying"] = "E",
        ["Singing"] = "C",
        ["Staff"] = "C+",
        ["String"] = "C",
        ["Sword"] = "C-",
        ["Throwing"] = "E",
        ["Wind"] = "C",
    },
    ["BST"] = {
        ["Axe"] = "A+",
        ["Club"] = "D",
        ["Dagger"] = "C+",
        ["Evasion"] = "C",
        ["Parrying"] = "C",
        ["Scythe"] = "B-",
        ["Shield"] = "E",
        ["Sword"] = "E",
    },
    ["COR"] = {
        ["Dagger"] = "B+",
        ["Evasion"] = "D",
        ["Marksmanship"] = "B",
        ["Parrying"] = "A-",
        ["Sword"] = "B-",
        ["Throwing"] = "C+",
    },
    ["DNC"] = {
        ["Dagger"] = "A+",
        ["Evasion"] = "B+",
        ["Hand-to-Hand"] = "D",
        ["Parrying"] = "B",
        ["Sword"] = "D",
        ["Throwing"] = "C+",
    },
    ["DRG"] = {
        ["Club"] = "E",
        ["Dagger"] = "E",
        ["Evasion"] = "B",
        ["Parrying"] = "B-",
        ["Polearm"] = "A+",
        ["Staff"] = "B-",
        ["Sword"] = "C-",
    },
    ["DRK"] = {
        ["Axe"] = "B-",
        ["Club"] = "C-",
        ["Dagger"] = "C",
        ["Dark"] = "A-",
        ["Elemental"] = "B+",
        ["Enfeebling"] = "C",
        ["Evasion"] = "C",
        ["Great Axe"] = "B-",
        ["Great Sword"] = "A-",
        ["Marksmanship"] = "E",
        ["Parrying"] = "E",
        ["Scythe"] = "A+",
        ["Sword"] = "B-",
    },
    ["GEO"] = {
        ["Club"] = "B+",
        ["Dagger"] = "C-",
        ["Dark"] = "C",
        ["Elemental"] = "B+",
        ["Enfeebling"] = "C+",
        ["Evasion"] = "D",
        ["Geomancy"] = "C",
        ["Handbell"] = "C",
        ["Parrying"] = "E",
        ["Staff"] = "C+",
    },
    ["MNK"] = {
        ["Club"] = "C+",
        ["Evasion"] = "B+",
        ["Guarding"] = "A-",
        ["Hand-to-Hand"] = "A+",
        ["Parrying"] = "E",
        ["Staff"] = "B",
        ["Throwing"] = "E",
    },
    ["NIN"] = {
        ["Archery"] = "E",
        ["Club"] = "E",
        ["Dagger"] = "C+",
        ["Evasion"] = "A-",
        ["Great Katana"] = "C-",
        ["Hand-to-Hand"] = "E",
        ["Katana"] = "A+",
        ["Marksmanship"] = "C",
        ["Ninjutsu"] = "A-",
        ["Parrying"] = "A-",
        ["Sword"] = "C",
        ["Throwing"] = "A+",
    },
    ["PLD"] = {
        ["Club"] = "A-",
        ["Dagger"] = "C-",
        ["Divine"] = "B+",
        ["Enhancing"] = "D",
        ["Evasion"] = "C",
        ["Great Sword"] = "B",
        ["Healing"] = "C",
        ["Parrying"] = "C",
        ["Polearm"] = "E",
        ["Shield"] = "A+",
        ["Staff"] = "A-",
        ["Sword"] = "A+",
    },
    ["PUP"] = {
        ["Club"] = "D",
        ["Dagger"] = "C-",
        ["Evasion"] = "B",
        ["Guarding"] = "B-",
        ["Hand-to-Hand"] = "A+",
        ["Parrying"] = "D",
        ["Throwing"] = "C+",
    },
    ["RDM"] = {
        ["Archery"] = "D",
        ["Club"] = "D",
        ["Dagger"] = "B",
        ["Dark"] = "E",
        ["Divine"] = "E",
        ["Elemental"] = "C+",
        ["Enfeebling"] = "A+",
        ["Enhancing"] = "B+",
        ["Evasion"] = "D",
        ["Healing"] = "C-",
        ["Parrying"] = "E",
        ["Shield"] = "F",
        ["Sword"] = "B",
        ["Throwing"] = "F",
    },
    ["RNG"] = {
        ["Archery"] = "A+",
        ["Axe"] = "B-",
        ["Club"] = "E",
        ["Dagger"] = "B-",
        ["Evasion"] = "E",
        ["Marksmanship"] = "A+",
        ["Sword"] = "D",
        ["Throwing"] = "C-",
    },
    ["RUN"] = {
        ["Axe"] = "B-",
        ["Club"] = "C-",
        ["Divine"] = "B",
        ["Enhancing"] = "B-",
        ["Evasion"] = "B+",
        ["Great Axe"] = "B",
        ["Great Sword"] = "A+",
        ["Parrying"] = "A+",
        ["Sword"] = "A-",
    },
    ["SAM"] = {
        ["Archery"] = "C+",
        ["Club"] = "E",
        ["Dagger"] = "E",
        ["Evasion"] = "B+",
        ["Great Katana"] = "A+",
        ["Parrying"] = "A-",
        ["Polearm"] = "B-",
        ["Sword"] = "C+",
        ["Throwing"] = "C+",
    },
    ["SCH"] = {
        ["Club"] = "C+",
        ["Dagger"] = "D",
        ["Dark"] = "D",
        ["Divine"] = "D",
        ["Elemental"] = "D",
        ["Enfeebling"] = "D",
        ["Enhancing"] = "D",
        ["Evasion"] = "E",
        ["Healing"] = "D",
        ["Parrying"] = "E",
        ["Staff"] = "C+",
        ["Throwing"] = "D",
    },
    ["SMN"] = {
        ["Club"] = "C+",
        ["Dagger"] = "E",
        ["Evasion"] = "E",
        ["Staff"] = "B",
        ["Summoning"] = "A-",
    },
    ["THF"] = {
        ["Archery"] = "C-",
        ["Club"] = "E",
        ["Dagger"] = "A+",
        ["Evasion"] = "A+",
        ["Hand-to-Hand"] = "E",
        ["Marksmanship"] = "C+",
        ["Parrying"] = "A-",
        ["Shield"] = "F",
        ["Sword"] = "D",
        ["Throwing"] = "D",
    },
    ["WAR"] = {
        ["Archery"] = "D",
        ["Axe"] = "A-",
        ["Club"] = "B-",
        ["Dagger"] = "B-",
        ["Evasion"] = "C",
        ["Great Axe"] = "A+",
        ["Great Sword"] = "B+",
        ["Hand-to-Hand"] = "D",
        ["Marksmanship"] = "D",
        ["Parrying"] = "C-",
        ["Polearm"] = "B-",
        ["Scythe"] = "B+",
        ["Shield"] = "C+",
        ["Staff"] = "B",
        ["Sword"] = "B",
        ["Throwing"] = "D",
    },
    ["WHM"] = {
        ["Club"] = "B+",
        ["Divine"] = "A-",
        ["Enfeebling"] = "C",
        ["Enhancing"] = "C+",
        ["Evasion"] = "E",
        ["Healing"] = "A+",
        ["Shield"] = "D",
        ["Staff"] = "C+",
        ["Throwing"] = "E",
    },
}

return skillranks
